### ISSUE TITLE
Implementar um sistema de verificação de CPF do associado

### ISSUE THREAD

**Issue by diegosneves** [diegosneves/assembleia-vota#35]
-  **Tarefa Bônus 1** - Integração com sistemas externos
    - Integrar com um sistema que verifique, a partir do CPF do associado, se ele pode votar
        - GET [https://user-info.herokuapp.com/users/{cpf}](https://user-info.herokuapp.com/users/%7Bcpf%7D)
        - Caso o CPF seja inválido, a API retornará o HTTP Status 404 (Not found). Você pode usar geradores de CPF para gerar CPFs válidos
        - Caso o CPF seja válido, a API retornará se o usuário pode (ABLE_TO_VOTE) ou não pode (UNABLE_TO_VOTE) executar a operação. Essa operação retorna resultados aleatórios, portanto um mesmo CPF pode funcionar em um teste e não funcionar no outro.

- Payload:
```json
{
    "status": "ABLE_TO_VOTE"
}
```

```json
{
    "status": "UNABLE_TO_VOTE"
}
```

> Pode ser contornado devido ao link não estar funcionando no momento de criação deste projeto.
> Gerando de forma aleatória o retorno com base no CPF informado.

**Comment by diegosneves** [comment]
Foi criado uma nova API para auxiliar esse Projeto:

https://github.com/diegosneves/validator-fiscal

Repositório privado temporariamente.
---

[validator Fiscal swagger - local ](http://localhost:8001/swagger-ui/index.html)

---

 Adicionado no `compose.yaml`

```yaml
  validator-fiscal-app:
    image: diegoneves/validator-fiscal:latest
    container_name: validator_fiscal_api
    ports:
      - "8001:8001"
```

Na versao final devera ser algo parecido com isso:

```yaml
services:
  database:
    image: "mysql:latest"
    container_name: assembleia_mysql_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-mysql-assembleia:/var/lib/mysql

  validator-fiscal-app:
    image: diegoneves/validator-fiscal:latest
    container_name: validator_fiscal_api
    ports:
      - "8001:8001"

  assembleia-app:
    image: diegoneves/assembleia-vota:latest
    container_name: assembleia_vota_api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=assembleia_mysql_db
      - DB_PORT=3306
      - FISCAL_HOST=validator_fiscal_api
      - FISCAL_PORT=8001
    entrypoint: sh -c "dockerize -wait tcp://assembleia_mysql_db:3306 -timeout 60s && java -jar target/assembleia-vota.jar"

volumes:
  db-mysql-assembleia:

```
